# Generated by Django 5.2.1 on 2025-07-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0002_alter_currency_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
