# Generated by Django 5.2.1 on 2025-07-17 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_alter_currency_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='updated_at',
        ),
    ]
