# Generated by Django 5.2.1 on 2025-06-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_alter_invitation_expired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
