# Generated by Django 5.2.1 on 2025-06-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invitations", "0003_invitation_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
