services:
  web:
    environment:
      - DEBUG=${DEBUG:-1}
      - DJANGO_SETTINGS_MODULE=config.settings
      - GMAIL_ACCOUNTS=${GMAIL_ACCOUNTS}
    volumes:
      - ./apps:/app/apps
      - ./config:/app/config
      - ./templates:/app/templates
      - ./credentials:/usr/src/app/credentials
      - ./logs:/app/logs:rw
    ports:
      - "8000:8000"
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]

  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"