services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      cache_from:
        - fyndora:latest
        - fyndora:python-deps
        - fyndora:node-build
      args:
        BUILDKIT_INLINE_CACHE: 1
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=config.settings
    command: uv run python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true

  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

volumes:
  node_modules: