services:
  web:
    environment:
      - DEBUG=${DEBUG:-1}
      - DJANGO_SETTINGS_MODULE=config.settings
      - GMAIL_ACCOUNTS=${GMAIL_ACCOUNTS}
    volumes:
      - ./apps:/app/apps
      - ./config:/app/config
      - ./templates:/app/templates
      - ./tests:/app/tests
      - ./manage.py:/app/manage.py
      - ./static:/app/static
      - ./credentials:/usr/src/app/credentials
      - ./logs:/app/logs:rw
    ports:
      - "8000:8000"
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]

  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
    command: ["celery", "-A", "config", "worker", "-l", "info"]
    volumes:
      - ./apps:/app/apps
      - ./config:/app/config
      - ./templates:/app/templates
      - ./tests:/app/tests
      - ./manage.py:/app/manage.py
      - ./static:/app/static
      - ./credentials:/usr/src/app/credentials:ro
      - ./logs:/app/logs:rw
    environment:
      - DEBUG=${DEBUG:-0}
      - DJANGO_SETTINGS_MODULE=config.settings
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB:-fyndora}
      - POSTGRES_USER=${POSTGRES_USER:-fyndora}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - GMAIL_ACCOUNTS=${GMAIL_ACCOUNTS}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - redis
      - db

  tailwind:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    container_name: fyndora-tailwind
    volumes:
      - ./static/css:/app/static/css
      - ./templates:/app/templates:ro
      - ./package.json:/app/package.json:ro
      - ./package-lock.json:/app/package-lock.json:ro
    working_dir: /app
    command: npm run tailwind:watch
    restart: unless-stopped
    tty: true
    stdin_open: true
    user: "0:0"
    depends_on:
      - web