# Generated by Django 5.2.1 on 2025-07-25 17:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('attachment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.FileField(upload_to='attachments/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('spreadsheet', 'Spreadsheet')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Attachments',
            },
        ),
    ]
