# Generated by Django 5.2.1 on 2025-06-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attachments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
