# Generated by Django 5.2.1 on 2025-07-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_attachment_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('spreadsheet', 'Spreadsheet'), ('other', 'Other')], max_length=20),
        ),
    ]
