# Generated by Django 5.2.1 on 2025-06-11 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0002_teammember"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entry_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("income", "Income"),
                            ("disbursement", "Disbursement"),
                            ("remittance", "Remittance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved"),
                            ("flagged", "Flagged"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending_review",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Must be a Team Coordinator, Operations Reviewer, or Workspace Admin",
                        limit_choices_to={
                            "role__in": [
                                "workspace_admin",
                                "operations_reviewer",
                                "team_coordinator",
                            ]
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_entries",
                        to="teams.teammember",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        help_text="Must be a user with Submitter role",
                        limit_choices_to={"role": "submitter"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_entries",
                        to="teams.teammember",
                    ),
                ),
            ],
            options={
                "verbose_name": "entry",
                "verbose_name_plural": "entries",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
