# Generated by Django 5.2.1 on 2025-07-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="status_last_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
