# Generated by Django 5.2.1 on 2025-08-11 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0002_alter_entry_status_last_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={
                "ordering": ["-occurred_at", "-created_at"],
                "permissions": [
                    (
                        "change_other_submitters_entry",
                        "Can change other submitters entry",
                    )
                ],
                "verbose_name": "entry",
                "verbose_name_plural": "entries",
            },
        ),
    ]
