# Generated by Django 5.2.1 on 2025-06-19 19:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0002_remove_entry_submitted_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
