# Generated by Django 5.2.1 on 2025-08-20 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0003_alter_entry_options"),
        (
            "organizations",
            "0032_remove_organizationmember_unique_organization_member_and_more",
        ),
        ("teams", "0012_remove_teammember_unique_team_member_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="submitted_by_org_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entries",
                to="organizations.organizationmember",
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="submitted_by_team_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entries",
                to="teams.teammember",
            ),
        ),
    ]
