# Generated by Django 5.2.1 on 2025-06-26 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0004_alter_entry_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={
                "ordering": ["-submitted_at"],
                "permissions": [
                    ("upload_attachments", "Can upload attachments to entries"),
                    ("review_entries", "Can review and approve entries"),
                    ("flag_entries", "Can flag or comment on entries"),
                ],
                "verbose_name": "entry",
                "verbose_name_plural": "entries",
            },
        ),
    ]
