# Generated by Django 5.2.1 on 2025-08-25 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_alter_entry_submitted_by_org_member_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-occurred_at'], 'permissions': [('change_other_submitters_entry', 'Can change other submitters entry')], 'verbose_name': 'entry', 'verbose_name_plural': 'entries'},
        ),
    ]
