# Generated by Django 5.2.1 on 2025-06-30 07:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0005_alter_entry_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={
                "ordering": ["-submitted_at"],
                "verbose_name": "entry",
                "verbose_name_plural": "entries",
            },
        ),
    ]
