# Generated by Django 5.2.1 on 2025-06-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_alter_entry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
