# Generated by Django 5.2.1 on 2025-07-02 06:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0006_alter_entry_options"),
        ("entries", "0007_alter_entry_options"),
    ]

    operations = []
