# Generated by Django 5.2.1 on 2025-07-02 06:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0008_merge_20250702_0652"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={
                "ordering": ["-submitted_at", "-created_at"],
                "permissions": [
                    ("upload_attachments", "Can upload attachments to entries"),
                    ("review_entries", "Can review and approve entries"),
                    ("flag_entries", "Can flag or comment on entries"),
                ],
                "verbose_name": "entry",
                "verbose_name_plural": "entries",
            },
        ),
    ]
