# Generated by Django 5.2.1 on 2025-09-01 06:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                (
                    "audit_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("login_success", "Login Success"),
                            ("login_failed", "Login Failed"),
                            ("logout", "Logout"),
                            ("password_changed", "Password Changed"),
                            ("password_reset_requested", "Password Reset Requested"),
                            ("password_reset_completed", "Password Reset Completed"),
                            ("user_created", "User Created"),
                            ("user_updated", "User Updated"),
                            ("user_deleted", "User Deleted"),
                            ("user_profile_updated", "User Profile Updated"),
                            ("organization_created", "Organization Created"),
                            ("organization_updated", "Organization Updated"),
                            ("organization_deleted", "Organization Deleted"),
                            (
                                "organization_status_changed",
                                "Organization Status Changed",
                            ),
                            ("organization_archived", "Organization Archived"),
                            ("organization_activated", "Organization Activated"),
                            ("organization_closed", "Organization Closed"),
                            ("organization_member_added", "Organization Member Added"),
                            (
                                "organization_member_removed",
                                "Organization Member Removed",
                            ),
                            (
                                "organization_member_role_changed",
                                "Organization Member Role Changed",
                            ),
                            (
                                "organization_member_updated",
                                "Organization Member Updated",
                            ),
                            (
                                "organization_exchange_rate_created",
                                "Organization Exchange Rate Created",
                            ),
                            (
                                "organization_exchange_rate_updated",
                                "Organization Exchange Rate Updated",
                            ),
                            (
                                "organization_exchange_rate_deleted",
                                "Organization Exchange Rate Deleted",
                            ),
                            ("workspace_created", "Workspace Created"),
                            ("workspace_updated", "Workspace Updated"),
                            ("workspace_deleted", "Workspace Deleted"),
                            ("workspace_status_changed", "Workspace Status Changed"),
                            ("workspace_archived", "Workspace Archived"),
                            ("workspace_activated", "Workspace Activated"),
                            ("workspace_closed", "Workspace Closed"),
                            ("workspace_admin_changed", "Workspace Admin Changed"),
                            (
                                "workspace_reviewer_assigned",
                                "Workspace Reviewer Assigned",
                            ),
                            (
                                "workspace_exchange_rate_created",
                                "Workspace Exchange Rate Created",
                            ),
                            (
                                "workspace_exchange_rate_updated",
                                "Workspace Exchange Rate Updated",
                            ),
                            (
                                "workspace_exchange_rate_deleted",
                                "Workspace Exchange Rate Deleted",
                            ),
                            ("team_created", "Team Created"),
                            ("team_updated", "Team Updated"),
                            ("team_deleted", "Team Deleted"),
                            ("team_member_added", "Team Member Added"),
                            ("team_member_removed", "Team Member Removed"),
                            ("team_member_role_changed", "Team Member Role Changed"),
                            ("workspace_team_created", "Workspace Team Created"),
                            ("workspace_team_updated", "Workspace Team Updated"),
                            ("workspace_team_deleted", "Workspace Team Deleted"),
                            ("workspace_team_added", "Workspace Team Added"),
                            ("workspace_team_removed", "Workspace Team Removed"),
                            (
                                "workspace_team_remittance_rate_updated",
                                "Workspace Team Remittance Rate Updated",
                            ),
                            ("entry_created", "Entry Created"),
                            ("entry_updated", "Entry Updated"),
                            ("entry_deleted", "Entry Deleted"),
                            ("entry_status_changed", "Entry Status Changed"),
                            ("entry_submitted", "Entry Submitted"),
                            ("entry_reviewed", "Entry Reviewed"),
                            ("entry_approved", "Entry Approved"),
                            ("entry_rejected", "Entry Rejected"),
                            ("entry_flagged", "Entry Flagged"),
                            ("entry_unflagged", "Entry Unflagged"),
                            ("file_uploaded", "File Uploaded"),
                            ("file_downloaded", "File Downloaded"),
                            ("file_deleted", "File Deleted"),
                            ("attachment_added", "Attachment Added"),
                            ("attachment_removed", "Attachment Removed"),
                            ("attachment_updated", "Attachment Updated"),
                            ("remittance_created", "Remittance Created"),
                            ("remittance_updated", "Remittance Updated"),
                            ("remittance_deleted", "Remittance Deleted"),
                            ("remittance_status_changed", "Remittance Status Changed"),
                            ("remittance_paid", "Remittance Paid"),
                            ("remittance_partially_paid", "Remittance Partially Paid"),
                            ("remittance_overdue", "Remittance Overdue"),
                            ("remittance_canceled", "Remittance Canceled"),
                            ("invitation_sent", "Invitation Sent"),
                            ("invitation_accepted", "Invitation Accepted"),
                            ("invitation_declined", "Invitation Declined"),
                            ("invitation_expired", "Invitation Expired"),
                            ("invitation_canceled", "Invitation Canceled"),
                            ("invitation_resent", "Invitation Resent"),
                            ("exchange_rate_created", "Exchange Rate Created"),
                            ("exchange_rate_updated", "Exchange Rate Updated"),
                            ("exchange_rate_deleted", "Exchange Rate Deleted"),
                            ("currency_added", "Currency Added"),
                            ("currency_updated", "Currency Updated"),
                            ("currency_removed", "Currency Removed"),
                            ("permission_granted", "Permission Granted"),
                            ("permission_changed", "Permission Changed"),
                            ("permission_revoked", "Permission Revoked"),
                            ("role_assigned", "Role Assigned"),
                            ("role_removed", "Role Removed"),
                            ("access_denied", "Access Denied"),
                            (
                                "unauthorized_access_attempt",
                                "Unauthorized Access Attempt",
                            ),
                            ("data_exported", "Data Exported"),
                            ("data_imported", "Data Imported"),
                            ("report_generated", "Report Generated"),
                            ("bulk_operation", "Bulk Operation"),
                            ("email_sent", "Email Sent"),
                            ("email_failed", "Email Failed"),
                            ("notification_sent", "Notification Sent"),
                            ("system_error", "System Error"),
                            ("operation_failed", "Operation Failed"),
                        ],
                        max_length=100,
                    ),
                ),
                ("target_entity_id", models.UUIDField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "target_entity_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["target_entity_type", "target_entity_id"],
                        name="auditlog_au_target__986f88_idx",
                    ),
                    models.Index(
                        fields=["action_type"], name="auditlog_au_action__6ad037_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="auditlog_au_timesta_65cbff_idx"
                    ),
                    models.Index(
                        fields=["user"], name="auditlog_au_user_id_c91882_idx"
                    ),
                ],
            },
        ),
    ]
