# Generated by Django 5.2.1 on 2025-09-09 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auditlog", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("organizations", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="audittrail",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_trails",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="audittrail",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_trails",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["organization"], name="auditlog_au_organiz_1c008a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["workspace"], name="auditlog_au_workspa_c746e5_idx"
            ),
        ),
    ]
