# Generated by Django 5.2.1 on 2025-09-01 06:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Remittance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "remittance_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "due_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("partial", "Partially Paid"),
                            ("paid", "Paid"),
                            ("overpaid", "Overpaid"),
                            ("overdue", "Overdue"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("paid_within_deadlines", models.BooleanField(default=True)),
                ("is_overpaid", models.BooleanField(default=False)),
                ("review_notes", models.TextField(blank=True, null=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_remittances",
                        to="organizations.organizationmember",
                    ),
                ),
                (
                    "workspace_team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remittance",
                        to="workspaces.workspaceteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "remittance",
                "verbose_name_plural": "remittances",
                "ordering": ["-created_at"],
                "permissions": [
                    ("review_remittance", "Can review and confirm remittances"),
                    ("flag_remittance", "Can flag remittances"),
                ],
                "indexes": [
                    models.Index(
                        fields=["status"], name="remittance__status_feb3e3_idx"
                    ),
                    models.Index(
                        fields=["paid_within_deadlines"],
                        name="remittance__paid_wi_89ab71_idx",
                    ),
                ],
            },
        ),
    ]
