# Generated by Django 5.2.1 on 2025-06-30 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("remittance", "0002_remittance_confirmed_at_remittance_confirmed_by"),
        ("workspaces", "0005_alter_workspace_remittance_rate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="remittance",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="remittance",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("partial", "Partially Paid"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="remittance",
            index=models.Index(
                fields=["due_date"], name="remittance__due_dat_b70eef_idx"
            ),
        ),
    ]
