# Generated by Django 5.2.1 on 2025-07-02 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remittance', '0003_remittance_due_date_alter_remittance_status_and_more'),
        ('remittance', '0003_remittance_due_date_and_more'),
    ]

    operations = [
    ]
