# Generated by Django 5.2.1 on 2025-07-10 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittance', '0005_alter_remittance_workspace_team'),
        ('workspaces', '0008_alter_workspace_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remittance',
            name='workspace_team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remittance', to='workspaces.workspaceteam'),
        ),
    ]
