# Generated by Django 5.2.1 on 2025-07-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("remittance", "0006_alter_remittance_workspace_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remittance",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("partial", "Partially Paid"),
                    ("paid", "Paid"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
