# Generated by Django 5.2.1 on 2025-07-31 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittance', '0008_remove_remittance_remittance__due_dat_b70eef_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittance',
            name='is_overpaid',
            field=models.BooleanField(default=False),
        ),
    ]
