# Generated by Django 5.2.1 on 2025-07-31 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remittance', '0009_remittance_is_overpaid'),
        ('remittance', '0010_alter_remittance_options'),
    ]

    operations = [
    ]
