# Generated by Django 5.2.1 on 2025-08-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittance', '0011_merge_20250801_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remittance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overpaid', 'Overpaid'), ('overdue', 'Overdue'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
