# Generated by Django 5.2.1 on 2025-09-01 06:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        ('organizations', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('closed', 'Closed')], default='active', max_length=20)),
                ('remittance_rate', models.DecimalField(decimal_places=2, default=90.0, help_text='% obligation from entries (Default 90%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workspaces', to='organizations.organizationmember')),
                ('operations_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_workspaces', to='organizations.organizationmember')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='organizations.organization')),
                ('workspace_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_workspaces', to='organizations.organizationmember')),
            ],
            options={
                'verbose_name': 'workspace',
                'verbose_name_plural': 'workspaces',
                'ordering': ['-created_at'],
                'permissions': (('assign_teams', 'Can assign teams to workspace by WA and Org Owner'), ('add_workspace_entry', 'Can add workspace entry by WA and Org Owner'), ('change_workspace_entry', 'Can change workspace entry by WA and Org Owner'), ('delete_workspace_entry', 'Can delete workspace entry by WA and Org Owner'), ('view_workspace_entry', 'Can view workspace entry by WA and Org Owner'), ('view_workspace_teams_under_workspace', 'Can view workspace teams under workspace by WA ,OR,TC and Org Owner'), ('add_workspace_currency', 'Can add workspace currency by WA and Org Owner'), ('change_workspace_currency', 'Can change workspace currency by WA and Org Owner'), ('delete_workspace_currency', 'Can delete workspace currency by WA and Org Owner'), ('view_workspace_currency', 'Can view workspace currency by WA and Org Owner'), ('view_total_workspace_teams_entries', 'Can view total workspace teams entries by WA and Org Owner')),
            },
        ),
        migrations.CreateModel(
            name='WorkspaceExchangeRate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('workspace_exchange_rate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_added_%(class)s_set', to='organizations.organizationmember')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_approved_%(class)s_set', to='organizations.organizationmember')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='currencies.currency')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_exchange_rates', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Exchange Rate',
                'verbose_name_plural': 'Workspace Exchange Rates',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceTeam',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_team_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_remittance_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Overrides workspace default if set (percentage value between 0 and 100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_workspaces', to='teams.team')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_teams', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'workspace team',
                'verbose_name_plural': 'workspace teams',
                'ordering': ['-created_at'],
                'permissions': (('view_workspace_team', 'Can view workspace team by Assigned WA and Org Owner'), ('add_workspace_team_entry', 'Can add workspace team entry by Submitter and Org Owner'), ('change_workspace_team_entry', 'Can change workspace team entry by Submitter and Org Owner'), ('delete_workspace_team_entry', 'Can delete workspace team entry by Submitter and Org Owner')),
            },
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(fields=('organization', 'title'), name='unique_workspace_in_organization'),
        ),
        migrations.AddConstraint(
            model_name='workspaceexchangerate',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'currency', 'effective_date'), name='unique_workspace_exchange_rate'),
        ),
        migrations.AddConstraint(
            model_name='workspaceteam',
            constraint=models.UniqueConstraint(fields=('team', 'workspace'), name='unique_team_in_workspace'),
        ),
    ]
