# Generated by Django 5.2.1 on 2025-06-09 10:44

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_organizationmember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('closed', 'Closed')], default='active', max_length=20)),
                ('remittance_rate', models.DecimalField(decimal_places=2, default=90.0, help_text='% obligation from entries (Default 90%)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('expense', models.DecimalField(decimal_places=2, default=0.0, help_text='Collection of Teams Expense + Direct Expense from the Workspace Admin', max_digits=12)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workspaces', to='organizations.organizationmember')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='organizations.organization')),
                ('workspace_admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administered_workspaces', to='organizations.organizationmember')),
            ],
            options={
                'verbose_name': 'workspace',
                'verbose_name_plural': 'workspaces',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('organization_id', 'title'), name='unique_workspace_in_organization')],
            },
        ),
    ]
