# Generated by Django 5.2.1 on 2025-07-02 09:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0005_alter_workspace_remittance_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceteam",
            name="custom_remittance_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Overrides workspace default if set (percentage value between 0 and 100)",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
    ]
