# Generated by Django 5.2.1 on 2025-07-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0013_alter_workspace_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="end_date",
            field=models.DateField(),
        ),
    ]
