# Generated by Django 5.2.1 on 2025-07-17 05:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0005_currency_created_at_currency_updated_at'),
        ('workspaces', '0015_workspaceexchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceexchangerate',
            name='effective_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='workspaceexchangerate',
            unique_together={('workspace', 'currency', 'effective_date')},
        ),
    ]
