# Generated by Django 5.2.1 on 2025-07-18 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0017_alter_workspaceexchangerate_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspaceexchangerate",
            name="effective_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
