# Generated by Django 5.2.1 on 2025-07-24 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0020_alter_workspace_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['-created_at'], 'permissions': (('assign_teams', 'Can assign teams to workspace'), ('lock_workspace', 'Can lock workspace'), ('view_dashboard', 'Can view dashboard'), ('add_workspace_entry', 'Can add workspace entry'), ('change_workspace_entry', 'Can change workspace entry'), ('delete_workspace_entry', 'Can delete workspace entry'), ('view_workspace_entry', 'Can view workspace entry'), ('review_workspace_entry', 'Can review workspace entry'), ('upload_workspace_attachments', 'Can upload workspace attachments'), ('flag_workspace_entry', 'Can flag workspace entry'), ('export_workspace_report', 'Can export workspace report')), 'verbose_name': 'workspace', 'verbose_name_plural': 'workspaces'},
        ),
    ]
