# Generated by Django 5.2.1 on 2025-07-25 17:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0026_alter_workspace_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceexchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
