# Generated by Django 5.2.1 on 2025-07-31 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0027_alter_workspaceexchangerate_rate'),
        ('workspaces', '0028_alter_workspace_options'),
    ]

    operations = [
    ]
