# Generated by Django 5.2.1 on 2025-08-14 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0031_alter_workspaceteam_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workspace",
            options={
                "ordering": ["-created_at"],
                "permissions": (
                    (
                        "assign_teams",
                        "Can assign teams to workspace by WA and Org Owner",
                    ),
                    (
                        "add_workspace_entry",
                        "Can add workspace entry by WA and Org Owner",
                    ),
                    (
                        "change_workspace_entry",
                        "Can change workspace entry by WA and Org Owner",
                    ),
                    (
                        "delete_workspace_entry",
                        "Can delete workspace entry by WA and Org Owner",
                    ),
                    (
                        "view_workspace_entry",
                        "Can view workspace entry by WA and Org Owner",
                    ),
                    (
                        "view_workspace_teams_under_workspace",
                        "Can view workspace teams under workspace by WA ,OR,TC and Org Owner",
                    ),
                    (
                        "add_workspace_currency",
                        "Can add workspace currency by WA and Org Owner",
                    ),
                    (
                        "change_workspace_currency",
                        "Can change workspace currency by WA and Org Owner",
                    ),
                    (
                        "delete_workspace_currency",
                        "Can delete workspace currency by WA and Org Owner",
                    ),
                ),
                "verbose_name": "workspace",
                "verbose_name_plural": "workspaces",
            },
        ),
        migrations.AlterModelOptions(
            name="workspaceteam",
            options={
                "ordering": ["-created_at"],
                "permissions": (
                    (
                        "view_workspace_team",
                        "Can view workspace team by Assigned WA and Org Owner",
                    ),
                    (
                        "add_workspace_team_entry",
                        "Can add workspace team entry by Submitter and Org Owner",
                    ),
                    (
                        "change_workspace_team_entry",
                        "Can change workspace team entry by Submitter and Org Owner",
                    ),
                    (
                        "delete_workspace_team_entry",
                        "Can delete workspace team entry by Submitter and Org Owner",
                    ),
                ),
                "verbose_name": "workspace team",
                "verbose_name_plural": "workspace teams",
            },
        ),
    ]
