# Generated by Django 5.2.1 on 2025-08-18 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0034_alter_workspace_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workspace",
            name="expense",
        ),
    ]
