# Generated by Django 5.2.1 on 2025-06-10 11:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0004_remove_organization_unique_organization_and_more"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team_member_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("workspace_admin", "Workspace Admin"),
                            ("operations_reviewer", "Operations Reviewer"),
                            ("team_coordinator", "Team Coordinator"),
                            ("submitter", "Submitter"),
                            ("auditor", "Auditor"),
                        ],
                        default="submitter",
                        max_length=32,
                    ),
                ),
                (
                    "organization_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to="organizations.organizationmember",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "team member",
                "verbose_name_plural": "team members",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("team", "organization_member"),
                        name="unique_team_member",
                    )
                ],
            },
        ),
    ]
