# Generated by Django 5.2.1 on 2025-06-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_remove_organization_unique_organization_and_more'),
        ('teams', '0002_alter_team_team_coordinator'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='team',
            name='unique_team_in_workspace',
        ),
        migrations.RemoveField(
            model_name='team',
            name='workspace',
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_team'),
        ),
    ]
