# Generated by Django 5.2.1 on 2025-06-19 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teammember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='title',
            new_name='name',
        ),
    ]
