# Generated by Django 5.2.1 on 2025-06-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organization_owner'),
        ('teams', '0003_rename_title_team_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='team',
            name='unique_team',
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_team'),
        ),
    ]
