# Generated by Django 5.2.1 on 2025-06-23 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_organization'),
        ('teams', '0004_remove_team_unique_team_team_unique_team'),
    ]

    operations = [
    ]
