# Generated by Django 5.2.1 on 2025-06-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organization_options'),
        ('teams', '0005_merge_20250623_0550'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='team',
            name='unique_team',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='title',
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_team'),
        ),
    ]
