# Generated by Django 5.2.1 on 2025-07-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_remove_team_unique_team_team_unique_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='custom_remittance_rate',
        ),
    ]
