# Generated by Django 5.2.1 on 2025-07-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_remove_team_custom_remittance_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('submitter', 'Submitter'), ('auditor', 'Auditor')], default='submitter', max_length=32),
        ),
    ]
