# Generated by Django 5.2.1 on 2025-08-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0009_alter_team_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="role",
            field=models.CharField(
                choices=[
                    ("team_coordinator", "Team Coordinator"),
                    ("submitter", "Submitter"),
                    ("auditor", "Auditor"),
                ],
                default="submitter",
                max_length=32,
            ),
        ),
    ]
