# Generated by Django 5.2.1 on 2025-08-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0010_alter_teammember_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
