# Generated by Django 5.2.1 on 2025-06-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['-created_at'], 'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
    ]
