# Generated by Django 5.2.1 on 2025-06-10 02:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_organizationmember_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="organization",
            name="unique_organization",
        ),
        migrations.RemoveConstraint(
            model_name="organizationmember",
            name="unique_organization_member",
        ),
        migrations.RenameField(
            model_name="organization",
            old_name="organization_expense",
            new_name="expense",
        ),
        migrations.RenameField(
            model_name="organization",
            old_name="organization_owner",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="organizationmember",
            old_name="organization_id",
            new_name="organization",
        ),
        migrations.RenameField(
            model_name="organizationmember",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                fields=("owner", "title"), name="unique_organization"
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationmember",
            constraint=models.UniqueConstraint(
                fields=("organization", "user"), name="unique_organization_member"
            ),
        ),
    ]