# Generated by Django 5.2.1 on 2025-06-25 02:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0006_alter_organization_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "organization",
                "verbose_name_plural": "organizations",
            },
        ),
    ]
