# Generated by Django 5.2.1 on 2025-07-17 03:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0011_alter_organization_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ["-created_at"],
                "permissions": (
                    ("add_workspace", "Can add workspace"),
                    ("invite_org_member", "Can invite org member"),
                    ("add_org_entry", "Can add org entry"),
                ),
                "verbose_name": "organization",
                "verbose_name_plural": "organizations",
            },
        ),
    ]
