# Generated by Django 5.2.1 on 2025-07-17 09:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "organizations",
            "0013_alter_organizationexchangerate_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationexchangerate",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="organizationexchangerate",
            name="is_approved",
        ),
    ]
