# Generated by Django 5.2.1 on 2025-07-17 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0014_alter_organization_options"),
        ("organizations", "0014_remove_organizationexchangerate_approved_by_and_more"),
    ]

    operations = []
