# Generated by Django 5.2.1 on 2025-07-18 04:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "organizations",
            "0013_alter_organizationexchangerate_unique_together_and_more",
        ),
        ("organizations", "0014_alter_organization_options"),
    ]

    operations = []
