# Generated by Django 5.2.1 on 2025-07-18 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0015_merge_20250717_0952"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationexchangerate",
            name="effective_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
