# Generated by Django 5.2.1 on 2025-07-18 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0015_merge_20250718_1100"),
        ("organizations", "0016_alter_organizationexchangerate_effective_date"),
    ]

    operations = []
