# Generated by Django 5.2.1 on 2025-07-18 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0017_merge_20250718_1945"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationexchangerate",
            name="approved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_approved_%(class)s_set",
                to="organizations.organizationmember",
            ),
        ),
        migrations.AddField(
            model_name="organizationexchangerate",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
