# Generated by Django 5.2.1 on 2025-07-21 04:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0019_alter_organization_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ["-created_at"],
                "permissions": (
                    ("add_workspace", "Can add workspace"),
                    ("add_team", "Can add team"),
                    ("invite_org_member", "Can invite org member"),
                    ("add_org_entry", "Can add org entry"),
                    ("view_org_entry", "Can view org entry"),
                    ("change_org_entry", "Can change org entry"),
                    ("delete_org_entry", "Can delete org entry"),
                    ("edit_workspace_admin", "Can change workspace admin"),
                ),
                "verbose_name": "organization",
                "verbose_name_plural": "organizations",
            },
        ),
    ]
