# Generated by Django 5.2.1 on 2025-07-22 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_alter_organization_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationexchangerate',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='organizationexchangerate',
            name='is_approved',
        ),
    ]
