# Generated by Django 5.2.1 on 2025-07-28 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_merge_20250718_1945'),
        ('organizations', '0025_alter_organization_options'),
    ]

    operations = [
    ]
