# Generated by Django 5.2.1 on 2025-07-30 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0024_alter_organizationexchangerate_rate'),
        ('organizations', '0027_alter_organization_options'),
    ]

    operations = [
    ]
