# Generated by Django 5.2.1 on 2025-08-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0029_alter_organization_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["title"], name="organizatio_title_fd51d9_idx"),
        ),
    ]
