# Generated by Django 5.2.1 on 2025-08-18 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0030_organization_organizatio_title_fd51d9_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="expense",
        ),
    ]
